package com.atms.app.user.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("right", "id", Right.class);
		arp.addMapping("role", "id", Role.class);
		// Composite Primary Key order: right_id,role_id
		arp.addMapping("role_right", "right_id,role_id", RoleRight.class);
		arp.addMapping("user", "id", User.class);
		// Composite Primary Key order: role_id,user_id
		arp.addMapping("user_role", "role_id,user_id", UserRole.class);
	}
}

