package com.atms.app.user.entity;

import com.atms.app.user.entity.base.BaseRight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Right extends BaseRight<Right> {
	public static final Right dao = new Right();
}
