package com.atms.app.user.entity;

import com.atms.app.user.entity.base.BaseRoleRight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleRight extends BaseRoleRight<RoleRight> {
	public static final RoleRight dao = new RoleRight();
}
