package com.atms.app.user.entity;

import com.atms.app.user.entity.base.BaseUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole();
}
